function plot_partitions_erp(dataone, datatwo, datathree, electrode, design2, factor, results, start, endtime, cis)

    [low1, high1] = median_split(dataone, 1, design2);
    [low2, high2] = median_split(datatwo, 1, design2);
    [low3, high3] = median_split(datathree, 1, design2);


    ylimit = ylimit_finder([dataone,datatwo,datathree],electrode);
    start = 2.8;
    f1 = figure;

    % First subplot low PGI across partitions
    Ax = subplot(5, 2, 1);
    data = partitions_combine(low1.data, low2.data, low3.data, "PGI");
    generate_erp_plot(results, start, endtime, data, electrode, "none", false, "positive");
    h = get(gca, 'Children');
    h(8).Color = [0.8350 0.0780 0.1840];
    h(7).Color = [0.4660 0.8740 0.1880];
    h(6).Color = [0.3010 0.7450 0.9330];
    delete(h(2));
    delete(h(3));
    delete(h(4));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    legend("P1 PGI", "P2 PGI", "P3 PGI", "", "", "", 'location', 'eastoutside');
    tit = strcat("Low Group PGI through partitions @ ", electrode.electrode);
    title(tit);

    Ax = subplot(5, 2, 2);
    data = partitions_combine(high1.data, high2.data, high3.data, "PGI");
    generate_erp_plot(results, start, endtime, data, electrode, "none", false, "positive");
    h = get(gca, 'Children');
    h(8).Color = [0.8350 0.0780 0.1840];
    h(7).Color = [0.4660 0.8740 0.1880];
    h(6).Color = [0.3010 0.7450 0.9330];
    delete(h(2));
    delete(h(3));
    delete(h(4));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    legend('hide');
    tit = strcat("High Group PGI through partitions @ ", electrode.electrode);
    title(tit);

    Ax = subplot(5, 2, 3);
    data = partitions_combine(low1.data, low2.data, low3.data, "med");
    generate_erp_plot(results, start, endtime, data, electrode, "none", false, "positive");
    h = get(gca, 'Children');
    h(8).Color = 'r';
    h(7).Color = 'g';
    h(6).Color = 'b';
    delete(h(1));
    delete(h(2));
    delete(h(3));
    delete(h(4));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    legend("P1 Med", "P2 Med", "P3 Med", "", "", "", 'location', 'eastoutside');
    tit = strcat("Low Group Medium through partitions @ ", electrode.electrode);
    subtitle("");
    title(tit);

    Ax = subplot(5, 2, 4);
    data = partitions_combine(high1.data, high2.data, high3.data, "med");
    generate_erp_plot(results, start, endtime, data, electrode, "none", false, "positive");
    h = get(gca, 'Children');
    h(8).Color = 'r';
    h(7).Color = 'g';
    h(6).Color = 'b';
    delete(h(1));
    delete(h(2));
    delete(h(3));
    delete(h(4));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    legend('hide');
    tit = strcat("High Group Medium through partitions @ ", electrode.electrode);
    subtitle("");
    title(tit);

    Ax = subplot(5, 2, 5);
    generate_erp_plot(results, start, endtime, low1.data, electrode, "none", cis, "positive");
    h = get(gca, 'Children');
    delete(h(4));
    delete(h(5));
    delete(h(6));
    delete(h(7));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    tit = strcat("Low P1 ERP @ ", electrode.electrode);
    subtitle("");
    legend('location', 'eastoutside');
    title(tit);

    Ax = subplot(5, 2, 6);
    generate_erp_plot(results, start, endtime, high1.data, electrode, "none", cis, "positive");
    h = get(gca, 'Children');
    delete(h(4));
    delete(h(5));
    delete(h(6));
    delete(h(7));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    tit = strcat("High P1 ERP @ ", electrode.electrode);
    subtitle("");
    legend('hide')
    title(tit);

    Ax = subplot(5, 2, 7);
    generate_erp_plot(results, start, endtime, low2.data, electrode, "none", cis, "positive");
    h = get(gca, 'Children');
    delete(h(4));
    delete(h(5));
    delete(h(6));
    delete(h(7));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    tit = strcat("Low P2 ERP @ ", electrode.electrode);
    legend('location', 'eastoutside');
    subtitle("");
    title(tit);

    Ax = subplot(5, 2, 8);
    generate_erp_plot(results, start, endtime, high2.data, electrode, "none", cis, "positive");
    h = get(gca, 'Children');
    delete(h(4));
    delete(h(5));
    delete(h(6));
    delete(h(7));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    tit = strcat("High P2 ERP @ ", electrode.electrode);
    subtitle("");
    legend('hide');
    title(tit);

    Ax = subplot(5, 2, 9);
    generate_erp_plot(results, start, endtime, low3.data, electrode, "none", cis, "positive");
    h = get(gca, 'Children');
    delete(h(4));
    delete(h(5));
    delete(h(6));
    delete(h(7));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    tit = strcat("Low P3 ERP @ ", electrode.electrode);
    legend('location', 'eastoutside');
    subtitle("");
    title(tit);

    Ax = subplot(5, 2, 10);
    generate_erp_plot(results, start, endtime, high3.data, electrode, "none", cis, "positive");
    h = get(gca, 'Children');
    delete(h(4));
    delete(h(5));
    delete(h(6));
    delete(h(7));
    ylim(ylimit);
    PosVec = Ax.Position;
    Ax.Position = PosVec + [0 -0.02 0 0.02];
    hold on;
    tit = strcat("High P3 ERP @ ", electrode.electrode);
    subtitle("");
    legend('hide');
    title(tit);

    titles = strcat("Interactions through partitions Low vs High group ", factor);
    f1.Position = f1.Position + [0 -300 0 300];
    %sgtitle(titles);
    name = strcat(results, "/partitions/", factor, ' erpcombined.png');
    saveas(gcf, name);
end